"""Detector contract — the structural guard against shape-2 silent failures.

WHY THIS EXISTS
---------------
Today's session found that nearly every "detector" we examined had a
silent failure inside it:

  - drift_scanner reported clean=true while stdout listed 167 violations (D21)
  - canary reported caught=false when harvester was healthy (D18)
  - canary's cleanup orphaned its own queue entries (D40)
  - health_monitor claimed "process hung" while process was idle (D20)
  - arbitration override silently reverted supervisor writes (D29)
  - router_sql_live_audit (D35) would have reported 0 violations during
    development if tested only on in-memory fake data

The pattern: a detector's healthy-looking output is not the same as a
detector that would actually catch the thing it's supposed to catch.

The cure: every detector gets a contract test that constructs a
KNOWN-UNHEALTHY state and asserts the detector fires. If the detector
is a stub, a misconfigured classifier, or has wrong severity, the
contract test fails. "Running without firing" becomes impossible.

USAGE
-----
A detector is any code that:
  - consumes ground truth (a DB, a file, a process table, a log),
  - emits a verdict (True/False, clean/dirty, ok/alert, pass/fail), and
  - affects operator behavior based on that verdict.

For each detector, register a contract:

    from gdx_dispatch.tests.contracts.detector_contract import detector_contract

    def seed_orphan_row(engine):
        ... # INSERT a row with NULL company_id

    def assert_detector_fires(result):
        assert result.total_unattributed > 0

    @detector_contract(
        name="test_residue_sweep",
        description="D44 sweeper must catch NULL tenant-attribution rows",
        seed=seed_orphan_row,
        run=lambda eng: classify_table(eng, text, "widgets", {"company_id"}),
        assert_fires=assert_detector_fires,
    )
    def test_contract_test_residue_sweep():
        pass  # body auto-generated by decorator

The tests/contracts/ directory holds one contract per detector. Missing a
contract for a registered detector is itself a drift finding — the
``silent_failure_scanner`` catches that at Phase 4.
"""
from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from typing import Any

import pytest


@dataclass
class DetectorContract:
    """One contract per detector. Stored in DETECTOR_REGISTRY."""
    name: str
    description: str
    seed: Callable[[Any], None]   # seed(engine/state) -> None
    run: Callable[[Any], Any]     # run(engine/state) -> detector_result
    assert_fires: Callable[[Any], None]  # assert_fires(result) -> None or raises

    # Optional: a no-seed run that should NOT fire (negative test)
    assert_quiet: Callable[[Any], None] | None = None


DETECTOR_REGISTRY: dict[str, DetectorContract] = {}


def register_detector(contract: DetectorContract) -> None:
    """Register a detector contract. Called at import time from each
    detector's contract test module. The ``silent_failure_scanner`` uses
    this registry to enforce coverage.
    """
    if contract.name in DETECTOR_REGISTRY:
        raise ValueError(
            f"Detector {contract.name!r} already registered. "
            f"Each detector gets exactly one contract."
        )
    DETECTOR_REGISTRY[contract.name] = contract


def run_contract(contract: DetectorContract, state: Any) -> None:
    """Execute the contract against a given state (e.g. a fresh engine).

    Steps:
      1. seed(state) — inject the known-unhealthy condition
      2. result = run(state) — let the detector do its thing
      3. assert_fires(result) — prove the detector noticed

    Any failure surfaces as the original AssertionError with the
    detector's name in context.
    """
    try:
        contract.seed(state)
        result = contract.run(state)
        contract.assert_fires(result)
    except AssertionError as e:
        raise AssertionError(
            f"Detector contract failed: {contract.name} — "
            f"{contract.description}. Original: {e}"
        ) from e


def list_registered_detectors() -> list[str]:
    """Return the sorted names of every registered detector. Used by the
    silent_failure_scanner to check coverage."""
    return sorted(DETECTOR_REGISTRY.keys())


# ── Reusable fixture-style helpers ────────────────────────────────────────

@pytest.fixture
def detector_registry():
    """Access the DETECTOR_REGISTRY within a test. Snapshots and restores
    so parametrized tests don't accidentally persist registrations."""
    snapshot = dict(DETECTOR_REGISTRY)
    yield DETECTOR_REGISTRY
    DETECTOR_REGISTRY.clear()
    DETECTOR_REGISTRY.update(snapshot)
