"""The checked-in route-table snapshot — one way to build it, one way to check it.

`gdx_dispatch/openapi_routes.txt` is the app's published route table: one
`METHOD path` per line, sorted, generated — never edited by hand. It exists
so a PR that adds or removes a route shows it as a one-line reviewable diff,
and so a router that silently fails to import (app.py falls back to an
empty APIRouter) is caught as missing routes instead of shipping.

    python -m gdx_dispatch.tools.openapi_snapshot --write   # refresh the file
    python -m gdx_dispatch.tools.openapi_snapshot --check   # exit 1 on drift

`tests/test_openapi_snapshot_current.py` runs the same comparison in the
default suite. The full OpenAPI document is served live at `/openapi.json`;
until 2026-08-31 a 2.8 MB copy of it was checked in, stale for weeks, read
by nothing — and not even deterministic (a schema default baked a random
secret per process). The route table is the part that is stable and worth
pinning.

Caveat carried from memory: `app.openapi()` collapses duplicate
(method, path) registrations and names the LOSING handler's operation. For
exact handler resolution read the routers.
"""
from __future__ import annotations

import argparse
import pathlib
import sys
from typing import Any

SNAPSHOT = pathlib.Path(__file__).resolve().parents[1] / "openapi_routes.txt"
REGEN = "python -m gdx_dispatch.tools.openapi_snapshot --write"
_METHODS = ("get", "post", "put", "patch", "delete", "head", "options")
_HEADER = (
    "# Route table published by the app (METHOD path, sorted). Generated by\n"
    f"# `{REGEN}`; gated by tests/test_openapi_snapshot_current.py.\n"
    "# Full document: GET /openapi.json on a running instance.\n"
)


def build_spec() -> dict[str, Any]:
    """The app's OpenAPI document. Uses the module-level app: importing
    gdx_dispatch.app already built one; building a second is pure cost."""
    from gdx_dispatch.app import app

    return app.openapi()


def operations(spec: dict[str, Any]) -> set[tuple[str, str]]:
    """The route table as (METHOD, path) pairs — the part that must not drift."""
    out: set[tuple[str, str]] = set()
    for path, item in (spec.get("paths") or {}).items():
        for method in _METHODS:
            if method in item:
                out.add((method.upper(), path))
    return out


def render(ops: set[tuple[str, str]]) -> str:
    return _HEADER + "".join(f"{m} {p}\n" for m, p in sorted(ops))


def parse(text: str) -> set[tuple[str, str]]:
    out: set[tuple[str, str]] = set()
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        method, _, path = line.partition(" ")
        out.add((method, path))
    return out


def load_snapshot() -> set[tuple[str, str]]:
    return parse(SNAPSHOT.read_text(encoding="utf-8"))


def write_snapshot(ops: set[tuple[str, str]] | None = None) -> pathlib.Path:
    ops = ops if ops is not None else operations(build_spec())
    SNAPSHOT.write_text(render(ops), encoding="utf-8")
    return SNAPSHOT


def drift(live: set[tuple[str, str]], snap: set[tuple[str, str]]) -> tuple[list[str], list[str]]:
    """(missing_from_snapshot, gone_from_app) as 'METHOD path' strings."""
    fmt = lambda ops: sorted(f"{m} {p}" for m, p in ops)  # noqa: E731
    return fmt(live - snap), fmt(snap - live)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true", help="regenerate gdx_dispatch/openapi_routes.txt")
    g.add_argument("--check", action="store_true", help="exit 1 if the file has drifted from the app")
    args = ap.parse_args(argv)
    live = operations(build_spec())
    if args.write:
        print(f"wrote {write_snapshot(live)} ({len(live)} operations)")
        return 0
    added, removed = drift(live, load_snapshot())
    if not added and not removed:
        print(f"openapi_routes.txt is current ({len(live)} operations)")
        return 0
    print(f"openapi_routes.txt has drifted — run: {REGEN}")
    for op in added:
        print(f"  + {op}   (in the app, missing from the snapshot)")
    for op in removed:
        print(f"  - {op}   (in the snapshot, gone from the app)")
    return 1


if __name__ == "__main__":
    sys.exit(main())
