"""Scaffold a new product-class spec for the typed-catalog system.

Emits the three artifacts needed to add a new Class Table Inheritance leaf:
  1. SQLAlchemy <Class>Spec model (paste into gdx_dispatch/models/tenant_models.py)
  2. Router constants + serializer/persistence wiring (paste into
     gdx_dispatch/routers/catalog.py)
  3. Frontend registry entry (paste into gdx_dispatch/frontend/src/catalog/types.js)

Print-only by design. Mutating three files programmatically is fragile; the
scaffolder's value is in producing the boilerplate, not in editing.

Usage:
    python -m gdx_dispatch.tools.scaffold_product_class opener \\
        hp:int drive_type:str battery_backup:bool wifi_brand:str \\
        horsepower_equivalent:str lift_capacity_lbs:int \\
        max_door_height_ft:numeric warranty_years:int

Field type tokens:
    str       → String(255)
    str:N     → String(N)
    text      → Text
    int       → Integer
    bool      → Boolean
    numeric   → Numeric(10,2)
    numeric:P,S → Numeric(P,S)
"""
from __future__ import annotations

import sys
from dataclasses import dataclass


@dataclass
class FieldSpec:
    name: str
    sa_type: str
    py_type: str
    form_input: str

    @classmethod
    def parse(cls, token: str) -> "FieldSpec":
        if ":" not in token:
            raise ValueError(f"field token {token!r} must be name:type")
        name, _, type_spec = token.partition(":")
        type_part, _, type_arg = type_spec.partition(":")
        if type_part == "str":
            length = int(type_arg) if type_arg else 255
            return cls(name, f"String({length})", "str", "text")
        if type_part == "text":
            return cls(name, "Text", "str", "textarea")
        if type_part == "int":
            return cls(name, "Integer", "int", "number")
        if type_part == "bool":
            return cls(name, "Boolean", "bool", "checkbox")
        if type_part == "numeric":
            if type_arg:
                p, _, s = type_arg.partition(",")
                ps = (int(p), int(s) if s else 2)
            else:
                ps = (10, 2)
            return cls(name, f"Numeric({ps[0]}, {ps[1]})", "Decimal", "number")
        raise ValueError(f"unknown field type {type_part!r} (use str/text/int/bool/numeric)")


def emit_model(class_name: str, fields: list[FieldSpec]) -> str:
    cls = f"{class_name.capitalize()}Spec"
    table = f"{class_name.lower()}_specs"
    lines = [
        f'class {cls}(Base):',
        f'    """Class Table Inheritance — install attributes for catalog items',
        f'    where product_class={class_name.lower()!r}. 1:1 with custom_catalog_items.',
        f'    Generated by gdx_dispatch/tools/scaffold_product_class.py."""',
        f'    __tablename__ = "{table}"',
        '',
        '    catalog_item_id: Mapped[UUID] = mapped_column(',
        '        Uuid(as_uuid=True),',
        '        ForeignKey("custom_catalog_items.id", ondelete="CASCADE"),',
        '        primary_key=True,',
        '    )',
    ]
    for f in fields:
        if f.py_type == "Decimal":
            mapped = "Mapped[Decimal]"
        elif f.py_type == "int":
            mapped = "Mapped[int]"
        elif f.py_type == "bool":
            mapped = "Mapped[bool]"
        else:
            mapped = "Mapped[str]"
        lines.append(f'    {f.name}: {mapped} = mapped_column({f.sa_type}, nullable=True)')
    lines.extend([
        '    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, default=utcnow)',
        '    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, default=utcnow, onupdate=utcnow)',
        '',
        f'    item: Mapped[CustomCatalogItem] = relationship(back_populates="{class_name.lower()}_spec")',
    ])
    return "\n".join(lines)


def emit_router_patch(class_name: str, fields: list[FieldSpec]) -> str:
    cls_lower = class_name.lower()
    cls_upper = class_name.upper()
    field_list = ", ".join(f'"{f.name}"' for f in fields)
    return f'''
# 1. Add to PRODUCT_CLASSES_WITH_SPEC:
PRODUCT_CLASSES_WITH_SPEC = {{"door", {cls_lower!r}}}

# 2. Add the spec field whitelist:
{cls_upper}_SPEC_FIELDS = ({field_list},)

# 3. Add import at top of catalog.py:
from gdx_dispatch.models.tenant_models import {class_name.capitalize()}Spec

# 4. In _serialize_item, after the door branch:
if product_class == {cls_lower!r}:
    out["spec"] = _serialize_{cls_lower}_spec(getattr(item, "{cls_lower}_spec", None))

# 5. Add a sibling _serialize_<class>_spec helper (mirror _serialize_door_spec).

# 6. In add_catalog_item, after the door branch:
if product_class == {cls_lower!r} and payload.spec:
    spec_kwargs = {{k: payload.spec[k] for k in {cls_upper}_SPEC_FIELDS if k in payload.spec}}
    if spec_kwargs:
        db.add({class_name.capitalize()}Spec(catalog_item_id=row.id, **spec_kwargs))

# 7. In patch_catalog_item, mirror the door spec patch block for the new class.
'''


def emit_types_js(class_name: str, fields: list[FieldSpec]) -> str:
    cls_lower = class_name.lower()
    label = class_name.capitalize()
    field_entries = ",\n    ".join(
        f'{{ name: {f.name!r}, label: {f.name.replace("_", " ").title()!r}, type: {f.form_input!r} }}'
        for f in fields
    )
    table_columns = ",\n    ".join(
        f'{{ field: "spec.{f.name}", header: {f.name.replace("_", " ").title()!r} }}'
        for f in fields[:5]
    )
    return f"""// Add to gdx_dispatch/frontend/src/catalog/types.js registry:
{cls_lower}: {{
  key: '{cls_lower}',
  label: '{label}',
  formFields: [
    {field_entries},
  ],
  tableColumns: [
    {{ field: 'sku', header: 'SKU' }},
    {{ field: 'name', header: 'Name' }},
    {table_columns},
    {{ field: 'cost', header: 'Cost' }},
    {{ field: 'price', header: 'Price' }},
  ],
  defaultSpec: {{}},
}},
"""


def main(argv: list[str]) -> int:
    if len(argv) < 3:
        print(__doc__)
        return 2
    class_name = argv[1]
    try:
        fields = [FieldSpec.parse(tok) for tok in argv[2:]]
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    print(f"# === Scaffold for product_class={class_name!r} ===\n")
    print("# --- (1) Paste into gdx_dispatch/models/tenant_models.py near DoorSpec ---\n")
    print(emit_model(class_name, fields))
    print()
    print("# Also add to CustomCatalogItem:")
    print(f'    {class_name.lower()}_spec: Mapped["{class_name.capitalize()}Spec | None"] = relationship(')
    print('        back_populates="item",')
    print('        cascade="all, delete-orphan",')
    print('        uselist=False,')
    print('    )\n')
    print("# --- (2) Patches for gdx_dispatch/routers/catalog.py ---")
    print(emit_router_patch(class_name, fields))
    print("# --- (3) Frontend registry entry ---\n")
    print(emit_types_js(class_name, fields))
    print(f"# After applying all three: run pave on a test tenant, then pytest.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
