"""Door listings — the invariants that keep an unapproved door off the internet.

The feature's whole risk profile is that two semi-trusted sources (a tech in
the field, a customer in the portal) can create rows that a public website
renders. So these tests care much less about CRUD working and much more about:

  - a technician CANNOT publish (they hold inventory.write but not nav.office)
  - a submitter's row is FORCED to pending_review regardless of what they send
  - the public surfaces expose `published` rows ONLY
  - customer submission needs BOTH switches on, and defaults to off
"""
from __future__ import annotations

from uuid import UUID, uuid4

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient
from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from gdx_dispatch.core.audit import TenantBase
from gdx_dispatch.core.database import get_db
from gdx_dispatch.models.tenant_models import AppSettings, Customer, User
from gdx_dispatch.modules.door_listings import service
from gdx_dispatch.modules.door_listings.models import DoorListing
from gdx_dispatch.routers.auth import get_current_user
from gdx_dispatch.routers.door_listings import public_router, router

TENANT = "tenant-test"
_ADMIN_UID = "00000000-0000-0000-0000-0000000000a1"
_TECH_UID = "00000000-0000-0000-0000-0000000000t1".replace("t", "b")
_CUSTOMER_ID = "00000000-0000-0000-0000-0000000000c1"

# A real 4x4 PNG generated by Pillow. NOT hand-rolled: the previous fixture
# was a broken data stream, and it passed only because compress_for_web used
# to swallow the failure and store the original bytes unprocessed.
_PNG = bytes.fromhex(
    "89504e470d0a1a0a0000000d4948445200000004000000040802000000269309"
    "290000001449444154789c633c5161c300034c0c48003707004bc801849e5e42"
    "fa0000000049454e44ae426082"
)


def _make_app(role: str = "admin", uid: str = _ADMIN_UID, tmp_path=None) -> TestClient:
    engine = create_engine(
        "sqlite://", connect_args={"check_same_thread": False}, poolclass=StaticPool
    )
    TenantBase.metadata.create_all(engine, checkfirst=True)
    Session = sessionmaker(bind=engine, autoflush=False, autocommit=False)

    setup = Session()
    # Literal statements rather than f-string interpolation of the table name:
    # ruff's S608 flags the latter, and CI ratchets on total violation count.
    setup.execute(
        text(
            "CREATE TABLE IF NOT EXISTS tenant_module_grants (id TEXT PRIMARY KEY, "
            "tenant_id TEXT, module_key TEXT, granted_at TEXT, created_at TEXT, expires_at TEXT)"
        )
    )
    setup.execute(
        text(
            "CREATE TABLE IF NOT EXISTS company_module_grants (id TEXT PRIMARY KEY, "
            "company_id TEXT, module_key TEXT, granted_at TEXT, created_at TEXT, expires_at TEXT)"
        )
    )
    setup.execute(
        text(
            "INSERT INTO tenant_module_grants (id, tenant_id, module_key, granted_at, created_at) "
            "VALUES (:id, :tid, 'inventory', datetime('now'), datetime('now'))"
        ),
        {"id": "tmg-g", "tid": TENANT},
    )
    setup.execute(
        text(
            "INSERT INTO company_module_grants (id, company_id, module_key, granted_at, created_at) "
            "VALUES (:id, :tid, 'inventory', datetime('now'), datetime('now'))"
        ),
        {"id": "cmg-g", "tid": TENANT},
    )
    # require_permission resolves the caller's role from the tenant users table.
    setup.add(
        User(id=UUID(uid), email=f"{role}@example.com", password_hash="x",
             role=role, active=True, company_id=TENANT)
    )
    setup.commit()
    setup.close()

    def _override_db():
        db = Session()
        try:
            yield db
        finally:
            db.close()

    app = FastAPI()

    @app.middleware("http")
    async def inject_tenant(request, call_next):
        request.state.tenant = {"id": TENANT}
        return await call_next(request)

    app.include_router(router)
    app.include_router(public_router)
    app.dependency_overrides[get_db] = _override_db
    app.dependency_overrides[get_current_user] = lambda: {
        "user_id": uid, "sub": uid, "role": role, "tenant_id": TENANT,
    }
    tc = TestClient(app, raise_server_exceptions=True)
    tc._engine = engine  # type: ignore[attr-defined]
    tc._Session = Session  # type: ignore[attr-defined]
    return tc


@pytest.fixture()
def office(tmp_path, monkeypatch):
    monkeypatch.setenv("UPLOAD_DIR", str(tmp_path))
    tc = _make_app("admin", _ADMIN_UID)
    yield tc
    tc.app.dependency_overrides.clear()
    tc._engine.dispose()  # type: ignore[attr-defined]


@pytest.fixture()
def tech(tmp_path, monkeypatch):
    monkeypatch.setenv("UPLOAD_DIR", str(tmp_path))
    tc = _make_app("technician", _TECH_UID)
    yield tc
    tc.app.dependency_overrides.clear()
    tc._engine.dispose()  # type: ignore[attr-defined]


def _create(client: TestClient, **over) -> dict:
    body = {"title": "16x7 sandtone short panel", "listing_type": "used", "price": 450}
    body.update(over)
    r = client.post("/api/door-listings", json=body)
    assert r.status_code == 201, r.text
    return r.json()


def _add_photo(client: TestClient, listing_id: str) -> dict:
    r = client.post(
        f"/api/door-listings/{listing_id}/photos",
        files={"file": ("door.png", _PNG, "image/png")},
    )
    assert r.status_code == 201, r.text
    return r.json()


# ── the security invariant ───────────────────────────────────────────────────


def test_technician_cannot_publish(tech: TestClient):
    """THE invariant. A tech holds inventory.write but not nav.office."""
    listing = _create(tech)
    _add_photo(tech, listing["id"])
    r = tech.post(f"/api/door-listings/{listing['id']}/publish")
    assert r.status_code == 403, r.text


def test_technician_cannot_reject_or_mark_sold(tech: TestClient):
    listing = _create(tech)
    assert tech.post(
        f"/api/door-listings/{listing['id']}/reject", json={"reason": "nope"}
    ).status_code == 403
    assert tech.post(f"/api/door-listings/{listing['id']}/sold").status_code == 403


def test_tech_submission_is_forced_to_pending_review(tech: TestClient):
    """Status and source are server-decided; a client cannot talk its way in."""
    listing = _create(tech, featured=True)
    assert listing["status"] == "pending_review"
    assert listing["source"] == "tech"
    # `featured` is an office pin — a submitter must not be able to set it.
    assert listing["featured"] is False


def test_office_create_starts_as_draft(office: TestClient):
    listing = _create(office)
    assert listing["status"] == "draft"
    assert listing["source"] == "office"


def test_office_can_publish_and_it_needs_a_photo(office: TestClient):
    listing = _create(office)
    r = office.post(f"/api/door-listings/{listing['id']}/publish")
    assert r.status_code == 422, "a door with no picture should not publish"

    _add_photo(office, listing["id"])
    r = office.post(f"/api/door-listings/{listing['id']}/publish")
    assert r.status_code == 200, r.text
    assert r.json()["status"] == "published"
    assert r.json()["published_at"]


def test_reject_requires_a_reason(office: TestClient):
    listing = _create(office)
    assert office.post(
        f"/api/door-listings/{listing['id']}/reject", json={}
    ).status_code == 422
    r = office.post(
        f"/api/door-listings/{listing['id']}/reject", json={"reason": "cracked section"}
    )
    assert r.status_code == 200
    assert r.json()["rejection_reason"] == "cracked section"


def test_submitter_loses_edit_rights_once_published(tech: TestClient, office: TestClient):
    """A tech may fix their own pending row, but not one the office approved."""
    listing = _create(tech)
    r = tech.patch(
        f"/api/door-listings/{listing['id']}",
        json={"title": "16x7 sandtone, dented bottom", "listing_type": "used"},
    )
    assert r.status_code == 200, r.text

    # Force it published directly in the DB (the office path is covered above).
    Session = tech._Session  # type: ignore[attr-defined]
    s = Session()
    row = s.query(DoorListing).first()
    row.status = "published"
    s.commit()
    s.close()

    r = tech.patch(
        f"/api/door-listings/{listing['id']}",
        json={"title": "free door", "listing_type": "used"},
    )
    assert r.status_code == 403


# ── public exposure ──────────────────────────────────────────────────────────


def test_public_photo_404s_until_published(office: TestClient):
    listing = _create(office)
    photo = _add_photo(office, listing["id"])

    r = office.get(f"/public/door-listings/{photo['id']}.jpg")
    assert r.status_code == 404, "a draft's photo must not be publicly readable"

    office.post(f"/api/door-listings/{listing['id']}/publish")
    r = office.get(f"/public/door-listings/{photo['id']}.jpg")
    assert r.status_code == 200, r.text
    assert r.headers["cache-control"].startswith("public, max-age=")


def test_public_photo_404s_for_unknown_id(office: TestClient):
    assert office.get(f"/public/door-listings/{uuid4()}.jpg").status_code == 404


def test_call_for_price_does_not_leak_the_number(office: TestClient):
    listing = _create(office, price=450, price_display="call_for_price")
    assert listing["price"] is None, "price must not ship in a field the site merely hides"


# ── ordering + slugs ─────────────────────────────────────────────────────────


def test_gdx_stock_outranks_customer_listings(office: TestClient):
    """§7.1 — our doors sit above consignment, whatever the dates say."""
    Session = office._Session  # type: ignore[attr-defined]
    s = Session()
    s.add(DoorListing(title="customer door", slug="customer-door", source="customer",
                      status="published", listing_type="used"))
    s.add(DoorListing(title="gdx door", slug="gdx-door", source="office",
                      status="published", listing_type="used"))
    s.commit()
    rows = s.query(DoorListing).order_by(*service.public_ordering()).all()
    s.close()
    assert [r.source for r in rows][0] == "office"


def test_slug_stays_unique(office: TestClient):
    a = _create(office, title="16x7 white")
    b = _create(office, title="16x7 white")
    assert a["slug"] != b["slug"]


# ── the customer-submission gate ─────────────────────────────────────────────


def _gate_db(company_on: bool, customer_on: bool):
    """Build the two gate rows through the ORM.

    Deliberately NOT raw SQL: SQLAlchemy's Uuid type stores a 32-char hex
    string on SQLite, so a hand-written INSERT of the dashed form silently
    fails to match on lookup — the row is there and the query still returns
    nothing.
    """
    engine = create_engine(
        "sqlite://", connect_args={"check_same_thread": False}, poolclass=StaticPool
    )
    TenantBase.metadata.create_all(engine, checkfirst=True)
    s = sessionmaker(bind=engine, autoflush=False, autocommit=False)()
    s.add(AppSettings(company_name="GDX", customer_listings_enabled=company_on))
    s.add(
        Customer(
            id=UUID(_CUSTOMER_ID),
            company_id=TENANT,
            name="Acme",
            can_submit_listings=customer_on,
        )
    )
    s.commit()
    return s


@pytest.mark.parametrize(
    ("company_on", "customer_on", "expected"),
    [
        (False, False, False),
        (False, True, False),   # company kill-switch beats a per-customer grant
        (True, False, False),   # per-customer defaults off
        (True, True, True),     # both required
    ],
)
def test_customer_gate_needs_both_switches(company_on, customer_on, expected):
    s = _gate_db(company_on, customer_on)
    try:
        assert service.customer_may_submit(s, _CUSTOMER_ID) is expected
    finally:
        s.close()


def test_customer_gate_is_off_with_no_settings_row():
    """Absent config must fail closed, not open."""
    engine = create_engine(
        "sqlite://", connect_args={"check_same_thread": False}, poolclass=StaticPool
    )
    TenantBase.metadata.create_all(engine, checkfirst=True)
    s = sessionmaker(bind=engine)()
    try:
        assert service.company_listings_enabled(s) is False
        assert service.customer_may_submit(s, _CUSTOMER_ID) is False
    finally:
        s.close()


# ── public serialization ─────────────────────────────────────────────────────


def test_public_serialize_drops_internal_fields():
    """The website must never receive the moderation trail or provenance."""
    listing = DoorListing(
        title="16x7 white", slug="16x7-white", source="tech", status="published",
        listing_type="used", rejection_reason="was rejected once",
        submitted_by_user_id=UUID(_ADMIN_UID), source_job_id=UUID(_ADMIN_UID),
    )
    pub = service.serialize(listing, public=True)
    for leaked in (
        "status", "source", "rejection_reason", "submitted_by_user_id",
        "submitted_by_customer_id", "reviewed_by_user_id", "reviewed_at",
        "source_job_id", "sold_at",
    ):
        assert leaked not in pub, f"{leaked} must not reach the public feed"
    # But the website still needs the ranking signal.
    assert pub["gdx_owned"] is True


def test_public_serialize_marks_customer_doors_not_gdx_owned():
    listing = DoorListing(title="d", slug="d", source="customer", listing_type="used")
    assert service.serialize(listing, public=True)["gdx_owned"] is False


# ── portal gate ──────────────────────────────────────────────────────────────


def test_portal_submission_404s_when_gate_is_closed():
    """404 not 403 — a 403 confirms the feature exists to someone shut out."""
    from fastapi import HTTPException

    from gdx_dispatch.routers.portal import PortalPrincipal, _require_listing_submission

    s = _gate_db(company_on=False, customer_on=True)
    principal = PortalPrincipal(
        user_id=UUID(_ADMIN_UID), customer_id=UUID(_CUSTOMER_ID), role="customer"
    )
    try:
        with pytest.raises(HTTPException) as exc:
            _require_listing_submission(s, principal)
        assert exc.value.status_code == 404
    finally:
        s.close()


def test_portal_submission_allowed_when_both_switches_on():
    from gdx_dispatch.routers.portal import PortalPrincipal, _require_listing_submission

    s = _gate_db(company_on=True, customer_on=True)
    principal = PortalPrincipal(
        user_id=UUID(_ADMIN_UID), customer_id=UUID(_CUSTOMER_ID), role="customer"
    )
    try:
        _require_listing_submission(s, principal)  # must not raise
    finally:
        s.close()


# ── regressions found by the pre-commit adversarial audit ────────────────────


def test_publish_is_not_reachable_through_a_nav_key():
    """The publish boundary must not rest on a nav-visibility key.

    The first implementation gated approval on `inventory.write` + `nav.office`.
    Both are things an admin edits in the Roles UI, and `core/permissions.py`
    documents nav.* as "nav-visibility ONLY (no API route enforces these)" — so
    giving technicians office navigation, a change that looks purely cosmetic,
    silently handed them the ability to publish to the public internet.

    This pins the shape of the fix, not just one role's current perm list.
    """
    from gdx_dispatch.core.permissions import BUILTIN_ROLES, WILDCARD

    tech = BUILTIN_ROLES["technician"]
    assert "listings.publish" not in tech
    # ...and it must not be reachable by adding office nav to that role.
    assert "listings.publish" not in set(tech) | {"nav.office", "nav.admin"}

    # admin/owner resolve against live BUILTIN_ROLES, so they need no backfill.
    assert "listings.publish" in BUILTIN_ROLES["admin"]
    assert WILDCARD in BUILTIN_ROLES["owner"]

    # No other builtin role gets it implicitly — fail-closed by default.
    for role in ("dispatcher", "sales", "accounting", "viewer"):
        assert "listings.publish" not in BUILTIN_ROLES[role], role


def test_patch_does_not_wipe_fields_the_client_did_not_send(office: TestClient):
    """A one-word title fix must not blank the rest of the row.

    `_apply` used to setattr every field from the payload's defaults, so a PATCH
    carrying only {title} reset brand, model, material, R-value and qty — data a
    portal customer may have typed.
    """
    listing = _create(
        office, title="16x7 insulated", brand="Clopay", model="Gallery",
        material="steel", insulation_r=9.5, qty=3, has_windows=True,
        compare_at_price=900,
    )
    r = office.patch(f"/api/door-listings/{listing['id']}", json={"title": "16x7 insulated (dented)"})
    assert r.status_code == 200, r.text
    after = r.json()
    assert after["title"] == "16x7 insulated (dented)"
    assert after["brand"] == "Clopay"
    assert after["model"] == "Gallery"
    assert after["material"] == "steel"
    assert after["insulation_r"] == 9.5
    assert after["qty"] == 3
    assert after["has_windows"] is True
    assert after["compare_at_price"] == 900


def test_unprocessable_image_is_rejected_not_stored(office: TestClient):
    """Fail closed. Storing an image Pillow can't parse would ship it to a
    public page with its EXIF — including phone GPS — intact."""
    listing = _create(office)
    r = office.post(
        f"/api/door-listings/{listing['id']}/photos",
        files={"file": ("bad.png", b"\x89PNG\r\n\x1a\ngarbage-not-an-image", "image/png")},
    )
    assert r.status_code == 422, r.text
    assert office.get(f"/api/door-listings/{listing['id']}").json()["photos"] == []


def test_sold_door_cannot_be_republished_by_a_stray_click(office: TestClient):
    listing = _create(office)
    _add_photo(office, listing["id"])
    office.post(f"/api/door-listings/{listing['id']}/publish")
    office.post(f"/api/door-listings/{listing['id']}/sold")
    r = office.post(f"/api/door-listings/{listing['id']}/publish")
    assert r.status_code == 409, r.text


def test_publish_requires_a_price_or_call_for_price(office: TestClient):
    """A 'fixed' price listing with no number renders a blank price on the site."""
    listing = _create(office, price=None, price_display="fixed")
    _add_photo(office, listing["id"])
    r = office.post(f"/api/door-listings/{listing['id']}/publish")
    assert r.status_code == 422, r.text

    office.patch(f"/api/door-listings/{listing['id']}", json={"price_display": "call_for_price"})
    assert office.post(f"/api/door-listings/{listing['id']}/publish").status_code == 200


def test_publish_refuses_zero_quantity(office: TestClient):
    listing = _create(office, qty=0)
    _add_photo(office, listing["id"])
    assert office.post(f"/api/door-listings/{listing['id']}/publish").status_code == 422


# ── the unauthenticated public feed (v1.31.1) ────────────────────────────────
#
# Same trust argument as the photos: the feed is the advertisement. What these
# pin is that going keyless did NOT loosen the two invariants that matter —
# published-only, and no internal fields.


def test_public_feed_needs_no_auth_and_returns_published_only(office: TestClient):
    listing = _create(office)
    _add_photo(office, listing["id"])

    # Unpublished → invisible, even though the route needs no credentials.
    r = office.get("/public/door-listings.json")
    assert r.status_code == 200, r.text
    assert r.json()["data"] == []

    office.post(f"/api/door-listings/{listing['id']}/publish")
    r = office.get("/public/door-listings.json")
    rows = r.json()["data"]
    assert [x["title"] for x in rows] == ["16x7 sandtone short panel"]
    assert r.headers["cache-control"].startswith("public, max-age=")

    # The public serializer, not the internal one.
    for leaked in ("status", "source", "rejection_reason", "submitted_by_user_id"):
        assert leaked not in rows[0], f"{leaked} must not reach the public feed"

    # Sold drops off immediately.
    office.post(f"/api/door-listings/{listing['id']}/sold")
    assert office.get("/public/door-listings.json").json()["data"] == []


def test_public_feed_validates_listing_type(office: TestClient):
    assert office.get("/public/door-listings.json?listing_type=bogus").status_code == 422
    assert office.get("/public/door-listings.json?listing_type=quick_ship").json()["data"] == []


# ── the tech-mobile field screen ─────────────────────────────────────────────


def test_mine_filter_scopes_to_the_caller(tech: TestClient):
    """`?mine=1` is what the field screen calls.

    Uses ONE client so both rows live in the SAME engine — the fixtures build
    separate in-memory SQLite databases, so an earlier version of this test that
    took both `office` and `tech` was only ever exercising office-scoping while
    appearing to test the tech.
    """
    mine_row = _create(tech)  # submitted_by_user_id == _TECH_UID

    Session = tech._Session  # type: ignore[attr-defined]
    s = Session()
    s.add(DoorListing(title="somebody else's", slug="somebody-else",
                      source="tech", status="pending_review", listing_type="used",
                      submitted_by_user_id=UUID(_ADMIN_UID)))
    s.commit()
    s.close()

    everything = tech.get("/api/door-listings").json()
    assert len(everything["listings"]) == 2, "unfiltered still shows both"

    scoped = tech.get("/api/door-listings?mine=1").json()
    assert [r["id"] for r in scoped["listings"]] == [mine_row["id"]]
    # The badge must agree with the list it sits next to.
    assert scoped["pending_count"] == 1, scoped["pending_count"]
    assert everything["pending_count"] == 2


def test_mine_filter_is_not_a_security_boundary(tech: TestClient):
    """Deliberately pinning the LIMIT of ?mine=1 so nobody mistakes it for authz.

    Anyone who can reach this endpoint already holds inventory.read and can just
    omit the param. The filter is a convenience for the phone; the real boundary
    is listings.publish on the write path.
    """
    Session = tech._Session  # type: ignore[attr-defined]
    s = Session()
    s.add(DoorListing(title="office door with a price", slug="office-priced",
                      source="office", status="draft", listing_type="used",
                      price=9999, submitted_by_user_id=UUID(_ADMIN_UID)))
    s.commit()
    s.close()

    assert tech.get("/api/door-listings?mine=1").json()["listings"] == []
    unscoped = tech.get("/api/door-listings").json()["listings"]
    assert any(r["title"] == "office door with a price" for r in unscoped)
