"""Sprint phone-com pc-s8 — Phone.com integration Settings router.

Five endpoints under ``/api/settings/integrations/phone-com``. Mirrors the
shape of ``admin_ai_settings.py`` (Sprint 1.x-S26): control-plane DB for
token state, tenant-plane DB for cached account features (AppSettings).

Auth: ``gdx_dispatch.core.auth.get_current_user`` (SS-7 SPA path) — same pattern
that the rest of ``gdx_dispatch/routers/settings.py`` uses for the other
integrations.

The token is NEVER returned in any response — only ``token_set: bool``.
The webhook URL incorporates a per-tenant secret generated by
``key_storage.get_or_create_webhook_secret`` (pc-s2b) so a leaked URL
on its own is not enough to forge events.
"""
from __future__ import annotations

import logging
import os
from typing import Any
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Request, status
from pydantic import BaseModel, ConfigDict, Field, field_validator
from sqlalchemy.orm import Session

from gdx_dispatch.control.models import Tenant, TenantSettings
from gdx_dispatch.core.audit import log_audit_event_sync
from gdx_dispatch.core.auth import get_current_user
from gdx_dispatch.core.database import get_db, get_tenant_db
from gdx_dispatch.models.tenant_models import AppSettings
from gdx_dispatch.modules.phone_com import key_storage
from gdx_dispatch.modules.phone_com.client import PhoneComClient

log = logging.getLogger("gdx_dispatch.routers.phone_com_settings")

router = APIRouter(
    prefix="/api/settings/integrations/phone-com",
    tags=["settings", "phone-com"],
)


# ── auth helpers (mirror admin_ai_settings) ─────────────────────────────


def _coerce_tenant_uuid(user: dict[str, Any]) -> UUID:
    tid = user.get("tenant_id")
    if not tid:
        raise HTTPException(status_code=400, detail="missing tenant context")
    return tid if isinstance(tid, UUID) else UUID(str(tid))


def _coerce_user_id(user: dict[str, Any]) -> str:
    return str(user.get("user_id") or user.get("id") or user.get("sub") or "unknown")


def _require_admin(user: dict[str, Any]) -> dict[str, Any]:
    role = (user.get("role") or "").lower()
    if role not in ("admin", "owner", "superadmin"):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN, detail="admin only"
        )
    return user


# ── pydantic schemas ────────────────────────────────────────────────────


class PhoneComWebhookStatus(BaseModel):
    registered: bool
    callback_id: int | None
    listener_id: int | None
    recent_delivery_at: str | None


class PhoneComTokenDetails(BaseModel):
    """Surface ``GET /v4/oauth/access-token/details`` for the active token.
    ``null`` for permanent tokens minted in the Phone.com Console — that
    endpoint 404s for them. Always-null is fine."""
    scope: str | None = None
    expires_at: str | None = None
    last_used_at: str | None = None
    grant_type: str | None = None


class PhoneComSettingsOut(BaseModel):
    token_set: bool
    voip_id: int | None
    default_extension_id: str | None
    default_caller_id: str | None
    last_validated_at: str | None
    last_synced_at: str | None
    last_error: str | None
    account_features: dict[str, Any] | None
    webhook_status: PhoneComWebhookStatus
    token_details: PhoneComTokenDetails | None = None


class PhoneComSettingsPatchIn(BaseModel):
    model_config = ConfigDict(extra="forbid")
    token: str | None = Field(default=None, min_length=10, max_length=4000)
    voip_id: int | None = Field(default=None, gt=0)
    default_extension_id: str | None = Field(default=None, max_length=80)
    default_caller_id: str | None = Field(default=None, max_length=40)

    @field_validator("default_caller_id")
    @classmethod
    def _check_e164(cls, v: str | None) -> str | None:
        if v is None or v == "":
            return v
        # Loose E.164 sanity: '+' followed by 8-15 digits.
        digits = v.lstrip("+")
        if not v.startswith("+") or not digits.isdigit() or not (8 <= len(digits) <= 15):
            raise ValueError("default_caller_id must look like +<8-15 digits>")
        return v


# ── webhook URL builder ──────────────────────────────────────────────────


def _build_webhook_url(tenant_slug: str, webhook_secret: str) -> str:
    base = os.environ.get("TENANT_BASE_DOMAIN", "example.com").strip("/")
    return f"https://{tenant_slug}.{base}/api/webhooks/phone-com/{tenant_slug}/{webhook_secret}"


# ── state aggregation ────────────────────────────────────────────────────


def _phone_com_settings_state(
    tenant_id: UUID, control_db: Session, tenant_db: Session | None = None
) -> dict[str, Any]:
    """Build the public-safe state response — never includes the token."""
    settings = control_db.get(TenantSettings, tenant_id)

    # AppSettings lives on the tenant DB. The PATCH/test/delete endpoints
    # have a tenant_db; the GET endpoint passes one too.
    voip_id: int | None = None
    default_ext: str | None = None
    default_cid: str | None = None
    features: dict[str, Any] | None = None
    last_synced_at: str | None = None
    if tenant_db is not None:
        app = tenant_db.query(AppSettings).first()
        if app is not None:
            try:
                voip_id = int(app.phone_com_voip_id) if app.phone_com_voip_id else None
            except (TypeError, ValueError):
                voip_id = None
            default_ext = app.phone_com_default_extension_id
            default_cid = app.phone_com_default_caller_id
            features = app.phone_com_account_features
            # last_synced_at is added in Wave B / S17. Tolerate AppSettings
            # rows from before the column was added (tenant-plane is ORM-only,
            # so older paved tenants may lack the attribute until pave_tenant_db).
            ts = getattr(app, "phone_com_last_synced_at", None)
            last_synced_at = ts.isoformat() if ts else None

    webhook_secret_present = bool(
        settings is not None and settings.phone_com_webhook_secret
    )

    return {
        "token_set": bool(settings is not None and settings.phone_com_token_enc),
        "voip_id": voip_id,
        "default_extension_id": default_ext,
        "default_caller_id": default_cid,
        "last_validated_at": (
            settings.phone_com_token_last_validated_at.isoformat()
            if settings is not None and settings.phone_com_token_last_validated_at
            else None
        ),
        "last_error": (
            settings.phone_com_token_last_error if settings is not None else None
        ),
        "last_synced_at": last_synced_at,
        "account_features": features,
        "webhook_status": {
            "registered": webhook_secret_present,
            # Wave E / S9: read persisted IDs from tenant_settings.
            "callback_id": settings.phone_com_webhook_callback_id if settings else None,
            "listener_id": settings.phone_com_webhook_listener_id if settings else None,
            "recent_delivery_at": None,
        },
    }


# ── token validate + webhook setup ───────────────────────────────────────


def _validate_and_setup_phone_com(
    tenant_id: UUID,
    payload: PhoneComSettingsPatchIn,
    control_db: Session,
    tenant_db: Session,
) -> dict[str, Any]:
    """Apply the PATCH: persist non-token fields, set token if provided,
    validate via test_and_cache_account, and ensure the webhook is
    registered with Phone.com.

    Returns a dict suitable for the PATCH response — including the test
    result and the webhook status.
    """
    # 1. Tenant-plane writes (voip_id default + default_extension_id + default_caller_id)
    if any(
        field is not None
        for field in (
            payload.voip_id,
            payload.default_extension_id,
            payload.default_caller_id,
        )
    ):
        app = tenant_db.query(AppSettings).first()
        if app is None:
            app = AppSettings()
            tenant_db.add(app)
            tenant_db.commit()
        if payload.voip_id is not None:
            app.phone_com_voip_id = str(payload.voip_id)
        if payload.default_extension_id is not None:
            app.phone_com_default_extension_id = payload.default_extension_id or None
        if payload.default_caller_id is not None:
            app.phone_com_default_caller_id = payload.default_caller_id or None
        tenant_db.commit()

    # 2. Token rotation (if token provided, persist + validate)
    if payload.token is not None:
        key_storage.set_token(control_db, tenant_id, payload.token)
        validation = key_storage.test_and_cache_account(control_db, tenant_id)
    else:
        # No new token; if a token is already set, re-validate so the UI
        # can show fresh state. If no token set, skip the upstream call.
        if key_storage.get_token(control_db, tenant_id) is None:
            return {
                "ok": False,
                "error": "no token set",
                "voip_id": None,
                "account_name": None,
                "features_cached": False,
                "webhook_status": {"registered": False, "callback_id": None,
                                   "listener_id": None},
            }
        validation = key_storage.test_and_cache_account(control_db, tenant_id)

    if not validation.get("ok"):
        return validation | {
            "webhook_status": {"registered": False, "callback_id": None,
                               "listener_id": None},
        }

    # 3. Register webhook with Phone.com (idempotent via ensure_webhook)
    webhook_status = _ensure_webhook_registered(
        tenant_id, control_db, validation.get("voip_id"),
    )
    # Wave E / S9: persist Phone.com's returned IDs so the GET endpoint can
    # show them without re-calling Phone.com on every page load.
    if webhook_status.get("registered"):
        settings = control_db.get(TenantSettings, tenant_id)
        if settings is not None:
            settings.phone_com_webhook_callback_id = webhook_status.get("callback_id")
            settings.phone_com_webhook_listener_id = webhook_status.get("listener_id")
            control_db.commit()
    return validation | {"webhook_status": webhook_status}


def _ensure_webhook_registered(
    tenant_id: UUID, control_db: Session, voip_id: int | None,
) -> dict[str, Any]:
    """Register the per-tenant webhook with Phone.com via ensure_webhook."""
    if voip_id is None:
        return {"registered": False, "callback_id": None, "listener_id": None}
    tenant = control_db.get(Tenant, tenant_id)
    if tenant is None or not tenant.slug:
        return {"registered": False, "callback_id": None, "listener_id": None}

    secret = key_storage.get_or_create_webhook_secret(control_db, tenant_id)
    url = _build_webhook_url(tenant.slug, secret)
    token = key_storage.get_token(control_db, tenant_id)
    if token is None:
        return {"registered": False, "callback_id": None, "listener_id": None}

    try:
        with PhoneComClient(token=token, voip_id=voip_id) as c:
            result = c.ensure_webhook(name="gdx-phone-com", url=url)
        return {
            "registered": True,
            "callback_id": result.get("callback_id"),
            "listener_id": result.get("listener_id"),
        }
    except Exception as exc:  # noqa: BLE001
        log.exception("ensure_webhook_failed tenant=%s err=%s", tenant_id, exc)
        return {"registered": False, "callback_id": None, "listener_id": None,
                "error": str(exc)}


def _clear_phone_com_token(tenant_id: UUID, control_db: Session) -> None:
    key_storage.clear_token(control_db, tenant_id)


def _disconnect_phone_com_webhook(
    tenant_id: UUID, control_db: Session, tenant_db: Session,
) -> dict[str, Any]:
    """Remove the webhook from Phone.com + clear the local secret."""
    token = key_storage.get_token(control_db, tenant_id)
    voip_id: int | None = None
    if tenant_db is not None:
        app = tenant_db.query(AppSettings).first()
        if app is not None and app.phone_com_voip_id:
            try:
                voip_id = int(app.phone_com_voip_id)
            except (TypeError, ValueError):
                voip_id = None

    deleted = {"deleted_listeners": [], "deleted_callback": None}
    tenant = control_db.get(Tenant, tenant_id)
    if token and voip_id and tenant and tenant.slug:
        secret_enc = (
            (control_db.get(TenantSettings, tenant_id) or TenantSettings()).phone_com_webhook_secret
        )
        if secret_enc:
            try:
                with PhoneComClient(token=token, voip_id=voip_id) as c:
                    callbacks = c.list_callbacks()
                    secret = key_storage.get_or_create_webhook_secret(control_db, tenant_id)
                    expected_url = _build_webhook_url(tenant.slug, secret)
                    target = next(
                        (
                            cb for cb in (callbacks.get("items") or [])
                            if (cb.get("config") or {}).get("url") == expected_url
                        ),
                        None,
                    )
                    if target is not None:
                        deleted = c.disconnect_webhook(callback_id=target["id"])
            except Exception as exc:  # noqa: BLE001
                log.exception("disconnect_webhook_failed tenant=%s err=%s", tenant_id, exc)

    key_storage.clear_webhook_secret(control_db, tenant_id)
    return deleted


# ── full-resync runner (sync path, Celery wrapping deferred to pc-s15) ───


def _run_resync_sync(tenant_id: UUID, control_db: Session) -> dict[str, Any]:
    """Run the full resync inline. The user-initiated /sync-now path uses
    this directly so the response carries real counts. A future Celery
    wrapper can call the same function for periodic refresh."""
    from gdx_dispatch.modules.phone_com.sync import run_full_resync

    return run_full_resync(control_db, tenant_id)


class _DelayShim:
    """Compat shim: existing test mocks still patch ``phone_com_full_resync``.
    The real /sync-now endpoint runs sync inline; this shim is only invoked
    by direct unit tests and by future Celery-wired callers."""

    def delay(self, tenant_id: str) -> None:
        log.info("phone_com_full_resync.delay fired tenant=%s (no-op shim)", tenant_id)


phone_com_full_resync = _DelayShim()


# ── endpoints ────────────────────────────────────────────────────────────


@router.get("")
def get_phone_com_settings(
    user: dict[str, Any] = Depends(get_current_user),
    control_db: Session = Depends(get_db),
    tenant_db: Session = Depends(get_tenant_db),
) -> PhoneComSettingsOut:
    """Read state. Reachable by any authenticated user (knowing the
    integration is configured isn't sensitive)."""
    tid = _coerce_tenant_uuid(user)
    state = _phone_com_settings_state(tid, control_db, tenant_db)
    return PhoneComSettingsOut(**state)


@router.patch("")
def patch_phone_com_settings(
    payload: PhoneComSettingsPatchIn,
    request: Request,
    user: dict[str, Any] = Depends(get_current_user),
    control_db: Session = Depends(get_db),
    tenant_db: Session = Depends(get_tenant_db),
) -> dict[str, Any]:
    _require_admin(user)
    tid = _coerce_tenant_uuid(user)
    result = _validate_and_setup_phone_com(tid, payload, control_db, tenant_db)
    if not result.get("ok"):
        # Audit the failed attempt — token exposure not possible since we
        # never log the value.
        try:
            log_audit_event_sync(
                control_db,
                tenant_id=str(tid),
                user_id=_coerce_user_id(user),
                action="phone_com.settings_patch_failed",
                entity_type="tenant_settings",
                entity_id=str(tid),
                details={"error": result.get("error")},
                request=request,
            )
            control_db.commit()
        except Exception:
            log.exception("phone_com_settings audit failed")
        raise HTTPException(status_code=400, detail=result.get("error") or "validation failed")

    try:
        log_audit_event_sync(
            control_db,
            tenant_id=str(tid),
            user_id=_coerce_user_id(user),
            action="phone_com.settings_patched",
            entity_type="tenant_settings",
            entity_id=str(tid),
            details={
                "token_rotated": payload.token is not None,
                "voip_id_set": payload.voip_id is not None,
                "webhook_registered": result.get("webhook_status", {}).get("registered", False),
            },
            request=request,
        )
        control_db.commit()
    except Exception:
        log.exception("phone_com_settings audit failed")

    state = _phone_com_settings_state(tid, control_db, tenant_db)
    return {**state, "test_result": result, "webhook_status": result.get("webhook_status")}


@router.delete("/token")
def delete_phone_com_token(
    request: Request,
    user: dict[str, Any] = Depends(get_current_user),
    control_db: Session = Depends(get_db),
    tenant_db: Session = Depends(get_tenant_db),
) -> dict[str, Any]:
    _require_admin(user)
    tid = _coerce_tenant_uuid(user)
    deleted = _disconnect_phone_com_webhook(tid, control_db, tenant_db)
    _clear_phone_com_token(tid, control_db)
    try:
        log_audit_event_sync(
            control_db,
            tenant_id=str(tid),
            user_id=_coerce_user_id(user),
            action="phone_com.token_cleared",
            entity_type="tenant_settings",
            entity_id=str(tid),
            details={"deleted_callback": deleted.get("deleted_callback")},
            request=request,
        )
        control_db.commit()
    except Exception:
        log.exception("phone_com_settings audit failed")
    return {"cleared": True, "webhook_disconnect": deleted}


@router.post("/test")
def post_phone_com_test(
    user: dict[str, Any] = Depends(get_current_user),
    control_db: Session = Depends(get_db),
    tenant_db: Session = Depends(get_tenant_db),
) -> dict[str, Any]:
    _require_admin(user)
    tid = _coerce_tenant_uuid(user)
    return key_storage.test_and_cache_account(control_db, tid)


# ── P3.10: OAuth code-exchange (backend) ─────────────────────────────────


class _OAuthCodeIn(BaseModel):
    model_config = ConfigDict(extra="forbid")
    client_id: str = Field(min_length=1, max_length=200)
    client_secret: str = Field(min_length=1, max_length=400)
    code: str = Field(min_length=1, max_length=400)
    redirect_uri: str = Field(min_length=8, max_length=400)


@router.post("/oauth/exchange")
def post_oauth_exchange(
    payload: _OAuthCodeIn,
    request: Request,
    user: dict[str, Any] = Depends(get_current_user),
    control_db: Session = Depends(get_db),
    tenant_db: Session = Depends(get_tenant_db),
) -> dict[str, Any]:
    """Exchange a Phone.com auth-code for an access token, then store the
    token via the same key_storage path used by the paste-token flow.

    Backend-only this slice — the redirect-handler page that captures the
    code and POSTs here is the next slice.
    """
    _require_admin(user)
    tid = _coerce_tenant_uuid(user)
    try:
        result = PhoneComClient.exchange_auth_code(
            client_id=payload.client_id,
            client_secret=payload.client_secret,
            code=payload.code,
            redirect_uri=payload.redirect_uri,
        )
    except Exception as exc:  # noqa: BLE001
        raise HTTPException(status_code=400, detail=f"oauth exchange failed: {exc}") from exc

    token = result.get("access_token") or result.get("token")
    if not token:
        raise HTTPException(status_code=502, detail="phone.com response missing access_token")
    key_storage.set_token(control_db, tid, token, user_id=_coerce_user_id(user))
    validation = key_storage.test_and_cache_account(control_db, tid)
    if not validation.get("ok"):
        raise HTTPException(
            status_code=400,
            detail=validation.get("error") or "token validation failed",
        )
    webhook = _ensure_webhook_registered(tid, control_db, validation.get("voip_id"))
    if webhook.get("registered"):
        settings = control_db.get(TenantSettings, tid)
        if settings is not None:
            settings.phone_com_webhook_callback_id = webhook.get("callback_id")
            settings.phone_com_webhook_listener_id = webhook.get("listener_id")
            control_db.commit()
    try:
        log_audit_event_sync(
            control_db,
            tenant_id=str(tid),
            user_id=_coerce_user_id(user),
            action="phone_com.oauth_exchanged",
            entity_type="tenant_settings",
            entity_id=str(tid),
            details={"webhook_registered": webhook.get("registered", False)},
            request=request,
        )
        control_db.commit()
    except Exception:
        log.exception("phone_com_settings audit failed")
    return validation | {"webhook_status": webhook}


@router.get("/token-details")
def get_phone_com_token_details(
    user: dict[str, Any] = Depends(get_current_user),
    control_db: Session = Depends(get_db),
    tenant_db: Session = Depends(get_tenant_db),
) -> dict[str, Any]:
    """Calls ``GET /v4/oauth/access-token/details`` for the tenant's active
    token. Returns ``{"available": false}`` for permanent tokens (most of
    GDX today) since the introspection endpoint 404s for them."""
    _require_admin(user)
    tid = _coerce_tenant_uuid(user)
    token = key_storage.get_token(control_db, tid)
    if token is None:
        raise HTTPException(status_code=400, detail="no token set")
    voip_id: int | None = None
    if tenant_db is not None:
        app = tenant_db.query(AppSettings).first()
        if app is not None and app.phone_com_voip_id:
            try:
                voip_id = int(app.phone_com_voip_id)
            except (TypeError, ValueError):
                voip_id = None
    try:
        with PhoneComClient(token=token, voip_id=voip_id) as c:
            details = c.get_access_token_details()
    except Exception as exc:  # noqa: BLE001
        log.warning("phone_com.token_details upstream failed: %s", exc)
        # Generic error; full exception is logged above. (CodeQL stack-trace-exposure)
        return {"available": False, "error": "Upstream provider error"}
    if details is None:
        return {"available": False, "reason": "permanent_token"}
    return {
        "available": True,
        "scope": details.get("scope") or details.get("scopes"),
        "expires_at": details.get("expires_at") or details.get("expires"),
        "last_used_at": details.get("last_used_at"),
        "grant_type": details.get("grant_type"),
        "raw": details,
    }


@router.post("/sync-now")
def post_phone_com_sync_now(
    user: dict[str, Any] = Depends(get_current_user),
    control_db: Session = Depends(get_db),
) -> dict[str, Any]:
    """Run a full Phone.com → tenant-DB backfill inline. Returns counts.

    Synchronous on purpose — the first user-initiated catch-up is small
    enough (Phone.com pagination at 50/page, capped at 5000) and the user
    expects immediate "synced N calls" feedback. Periodic refresh moves
    to Celery in pc-s15.
    """
    _require_admin(user)
    tid = _coerce_tenant_uuid(user)
    # Keep the shim hook for tests that mock phone_com_full_resync.delay
    phone_com_full_resync.delay(str(tid))
    result = _run_resync_sync(tid, control_db)
    if not result.get("ok"):
        # Surface the upstream Phone.com error (e.g. "401 oauth2.access_denied")
        # — it's an actionable provider status for the admin, not an internal
        # trace. (CodeQL stack-trace-exposure #38: dismissed as intentional.)
        raise HTTPException(status_code=502, detail=result.get("error") or "sync failed")
    return result
