"""Sub-resource endpoints for customers and jobs.

Originally written to replace shim endpoints from ui_compat.py with real
DB-backed implementations. Generated by Gemma 4 26B, reviewed and applied by
Claude.

2026-08-24. The replacement was never finished on the ui_compat side: the shims
this file supersedes stayed in place, so several paths had TWO definitions.
This router registers at app.py:1677, ahead of ui_compat at :1682, so its copy
always won and the ui_compat copy was unreachable dead code. Anyone auditing
ui_compat by reading it would have described behaviour that never runs — that
is exactly how `GET /api/customers/{id}/recurring-jobs` got written up as
"returns a hardcoded empty list" when the live handler here queries
`recurring_job_schedules` for real.

The billing and AI-quality blocks were removed 2026-08-24 (owner decision,
docs/design/unimplemented-endpoints-decision-list.md items 16 and 17): six
handlers with no UI caller anywhere. `/api/billing/subscription` was the worst
of them — it answered a hardcoded `{"plan": "pro", "status": "active",
"seats": 5}`, SaaS-plan fiction in a single-tenant app. Removing them from
ui_compat alone would have changed nothing, because these copies were the ones
being served.
"""
from __future__ import annotations

import logging
from datetime import UTC, datetime
from uuid import uuid4

from fastapi import APIRouter, Depends, HTTPException, Request
from sqlalchemy import select, text
from sqlalchemy.orm import Session

from gdx_dispatch.core.audit import log_audit_event_sync
from gdx_dispatch.core.database import get_db
from gdx_dispatch.core.tenant import company_id
from gdx_dispatch.models.tenant_models import Invoice
from gdx_dispatch.routers.auth import get_current_user

log = logging.getLogger(__name__)
router = APIRouter(tags=["sub-resources"])


@router.get("/api/customers/{customer_id}/recurring-jobs")
def customer_recurring_jobs(customer_id: str, user: dict = Depends(get_current_user), db: Session = Depends(get_db)):
    # Table is `recurring_job_schedules` and the date column is `next_run`
    # (aliased to next_run_at for the frontend) — the old query named a
    # nonexistent "recurring_jobs" table with title/next_due columns, so it
    # ALWAYS threw UndefinedTable and returned empty: every customer showed
    # "No recurring jobs" regardless of their schedules. A left join pulls
    # the template name for the row title. Found in the 2026-07-15 walk.
    try:
        rows = db.execute(
            text(
                """
                SELECT s.id, s.customer_id, s.frequency, s.status, s.created_at,
                       s.next_run AS next_run_at, t.title AS template_name
                FROM recurring_job_schedules s
                LEFT JOIN job_templates t ON t.id = s.job_template_id
                WHERE s.customer_id = :cid AND s.deleted_at IS NULL
                ORDER BY s.next_run NULLS LAST
                """
            ),
            {"cid": customer_id},
        ).mappings().all()
        return {"items": [dict(r) for r in rows], "total": len(rows)}
    except Exception:
        log.exception("customer_recurring_jobs_query_failed")
        return {"items": [], "total": 0}


@router.post("/api/customers/{customer_id}/optout")
def customer_optout(customer_id: str, request: Request, user: dict = Depends(get_current_user), db: Session = Depends(get_db)):
    tenant_id = company_id()
    user_id = user.get("sub") or user.get("user_id") or "system"
    log_audit_event_sync(db, tenant_id=tenant_id, user_id=user_id, action="customer_optout", entity_type="customer", entity_id=customer_id, details={}, request=request)
    db.commit()
    return {"ok": True, "opted_out": True}


@router.get("/api/jobs/{job_id}/line-items")
def job_line_items(job_id: str, user: dict = Depends(get_current_user), db: Session = Depends(get_db)):
    try:
        from gdx_dispatch.models.tenant_models import InvoiceLine
        rows = db.execute(
            select(InvoiceLine).join(Invoice, InvoiceLine.invoice_id == Invoice.id).where(
                Invoice.job_id == job_id,
                Invoice.deleted_at.is_(None),
            ).order_by(InvoiceLine.sort_order)
        ).scalars().all()
        return {"items": [{"id": str(r.id), "description": r.description, "quantity": r.quantity, "unit_price": float(r.unit_price or 0), "line_total": float(r.line_total or 0), "created_at": str(r.created_at) if r.created_at else None} for r in rows], "total": len(rows)}
    except Exception:
        log.exception("job_line_items_query_failed")
        return {"items": [], "total": 0}


@router.post("/api/jobs/{job_id}/line-items", status_code=201)
def create_job_line_item(job_id: str, request: Request, payload: dict, user: dict = Depends(get_current_user), db: Session = Depends(get_db)):
    tenant_id = company_id()
    user_id = user.get("sub") or user.get("user_id") or "system"
    invoice_id = payload.get("invoice_id")
    if not invoice_id:
        raise HTTPException(400, "invoice_id required")
    new_id = str(uuid4())
    qty = int(payload.get("quantity", 1))
    price = float(payload.get("unit_price", 0))
    line_total = qty * price
    now = datetime.now(UTC)
    try:
        from uuid import UUID as _UUID

        from gdx_dispatch.models.tenant_models import InvoiceLine
        try:
            _inv_uuid = _UUID(invoice_id)
        except (ValueError, AttributeError):
            raise HTTPException(400, "invalid invoice_id") from None
        line = InvoiceLine(
            id=new_id,
            company_id=tenant_id,
            invoice_id=_inv_uuid,
            description=payload.get("description", ""),
            quantity=qty,
            unit_price=price,
            line_total=line_total,
            sort_order=999,
            created_at=now,
        )
        db.add(line)
        db.commit()
    except HTTPException:
        raise
    except Exception:
        log.exception("create_line_item_failed")
        db.rollback()
        raise HTTPException(500, "Failed to create line item") from None
    log_audit_event_sync(db, tenant_id=tenant_id, user_id=user_id, action="create_line_item", entity_type="invoice_line", entity_id=new_id, details={"job_id": job_id, "invoice_id": invoice_id}, request=request)
    return {"ok": True, "id": new_id}


