"""Sub-resource endpoints for customers and jobs.

Originally written to replace shim endpoints from ui_compat.py with real
DB-backed implementations. Generated by Gemma 4 26B, reviewed and applied by
Claude.

2026-08-24. The replacement was never finished on the ui_compat side: the shims
this file supersedes stayed in place, so several paths had TWO definitions.
This router registers at app.py:1677, ahead of ui_compat at :1682, so its copy
always won and the ui_compat copy was unreachable dead code. Anyone auditing
ui_compat by reading it would have described behaviour that never runs — that
is exactly how `GET /api/customers/{id}/recurring-jobs` got written up as
"returns a hardcoded empty list" when the live handler here queries
`recurring_job_schedules` for real.

The billing and AI-quality blocks were removed 2026-08-24 (owner decision,
decision-list items 16 and 17): six
handlers with no UI caller anywhere. `/api/billing/subscription` was the worst
of them — it answered a hardcoded `{"plan": "pro", "status": "active",
"seats": 5}`, SaaS-plan fiction in a single-tenant app. Removing them from
ui_compat alone would have changed nothing, because these copies were the ones
being served.
"""
from __future__ import annotations

import logging
from datetime import UTC, datetime
from uuid import UUID, uuid4

from fastapi import APIRouter, Depends, HTTPException, Request
from pydantic import BaseModel, Field
from sqlalchemy import select, text
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from gdx_dispatch.core.audit import (
    ensure_audit_table,
    log_audit_event_sync,
    resolve_audit_actor,
)
from gdx_dispatch.core.database import get_db
from gdx_dispatch.core.modules import require_permission
from gdx_dispatch.core.tenant import company_id
from gdx_dispatch.models.tenant_models import Invoice
from gdx_dispatch.routers.auth import get_current_user

log = logging.getLogger(__name__)
router = APIRouter(tags=["sub-resources"])


@router.get("/api/customers/{customer_id}/recurring-jobs")
def customer_recurring_jobs(customer_id: str, user: dict = Depends(get_current_user), db: Session = Depends(get_db)):
    # Table is `recurring_job_schedules` and the date column is `next_run`
    # (aliased to next_run_at for the frontend) — the old query named a
    # nonexistent "recurring_jobs" table with title/next_due columns, so it
    # ALWAYS threw UndefinedTable and returned empty: every customer showed
    # "No recurring jobs" regardless of their schedules. A left join pulls
    # the template name for the row title. Found in the 2026-07-15 walk.
    try:
        rows = db.execute(
            text(
                """
                SELECT s.id, s.customer_id, s.frequency, s.status, s.created_at,
                       s.next_run AS next_run_at, t.title AS template_name
                FROM recurring_job_schedules s
                LEFT JOIN job_templates t ON t.id = s.job_template_id
                WHERE s.customer_id = :cid AND s.deleted_at IS NULL
                ORDER BY s.next_run NULLS LAST
                """
            ),
            {"cid": customer_id},
        ).mappings().all()
        return {"items": [dict(r) for r in rows], "total": len(rows)}
    except Exception:
        log.exception("customer_recurring_jobs_query_failed")
        return {"items": [], "total": 0}


@router.post("/api/customers/{customer_id}/optout")
def customer_optout(customer_id: str, request: Request, user: dict = Depends(get_current_user), db: Session = Depends(get_db)):
    tenant_id = company_id()
    user_id = user.get("sub") or user.get("user_id") or "system"
    log_audit_event_sync(db, tenant_id=tenant_id, user_id=user_id, action="customer_optout", entity_type="customer", entity_id=customer_id, details={}, request=request)
    db.commit()
    return {"ok": True, "opted_out": True}


class BulkTagIn(BaseModel):
    """Typed on purpose. The previous handler took a raw `dict`, which is how
    the sibling `create_job_line_item` ended up the one writer that could put a
    0 on an invoice line (#560): a raw dict runs no validation at all."""

    customer_ids: list[str] = Field(min_length=1, max_length=500)
    tag: str = Field(min_length=1, max_length=80)


@router.post(
    "/api/customers/bulk-tag",
    dependencies=[Depends(require_permission("customers.write"))],
)
def customers_bulk_tag(
    payload: BulkTagIn,
    request: Request,
    user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Apply one tag, by name, to many customers.

    This replaces a stub that returned `{"ok": True, "tagged": len(ids)}` with
    no database session at all — it took no `db`, wrote nothing, audited
    nothing, and reported success. The Segments toolbar calls it and toasts
    "Tag applied to selected customers", so office staff were told a tag landed
    on every selection and none ever did. `ui_compat` held a second copy that
    correctly raised 501; `sub_resources` is included first, so the honest one
    was the unreachable one.

    The UI field is free text ("Tag name"), and `tags.name` is unique per
    tenant with soft-delete resurrection, so the name is the natural key:
    find-or-create, matching `POST /api/tags` semantics rather than inventing
    new ones.

    Assignment goes through `tags._assign_tag`, which already writes the
    `tag_assigned` audit row (invariant #1) and is idempotent on re-tagging.
    Re-implementing it here would have duplicated both.
    """
    from gdx_dispatch.models.tenant_models import Customer, Tag
    from gdx_dispatch.routers.tags import _assign_tag

    tenant_id = company_id()
    name = payload.tag.strip()
    if not name:
        raise HTTPException(422, "tag name cannot be blank")

    requested = list(dict.fromkeys(payload.customer_ids))  # de-dup, keep order

    # `Customer.id` is Uuid(as_uuid=True): Postgres accepts a string, SQLite
    # calls `value.hex` and raises. Coerce for the QUERY and keep the strings
    # for the response and for `entity_id`, which is free-form text. Same
    # dialect split as #631.
    # A malformed id simply cannot match a row, so it falls into `missing`
    # below with every other unknown id — no separate bucket, which is why an
    # earlier `malformed` list here was dead code the audit caught.
    as_uuid: dict[str, UUID] = {}
    for cid in requested:
        try:
            as_uuid[cid] = UUID(str(cid))
        except (ValueError, AttributeError, TypeError):
            continue

    # Only tag customers that exist and are not soft-deleted. The assignment
    # table takes a free-form entity_id, so without this a typo would create a
    # tidy-looking assignment row pointing at nothing.
    live_ids: set[str] = set()
    if as_uuid:
        live = db.execute(
            select(Customer.id).where(
                Customer.id.in_(list(as_uuid.values())),
                Customer.deleted_at.is_(None),
            )
        ).scalars().all()
        found = {str(c) for c in live}
        live_ids = {cid for cid in as_uuid if str(as_uuid[cid]) in found}
    missing = [c for c in requested if c not in live_ids]

    ensure_audit_table(db)

    # Find-or-create the tag, resurrecting a soft-deleted one by the same name
    # exactly as POST /api/tags does.
    tag = db.execute(select(Tag).where(Tag.name == name)).scalar_one_or_none()
    created = False
    if tag is None:
        tag = Tag(company_id=tenant_id, name=name)
        db.add(tag)
        try:
            db.commit()
        except IntegrityError:
            # Concurrent create of the same name. POST /api/tags answers 409
            # rather than 500; match it instead of inventing a second contract.
            db.rollback()
            tag = db.execute(select(Tag).where(Tag.name == name)).scalar_one_or_none()
            if tag is None:
                raise HTTPException(409, "Tag name already exists") from None
        else:
            created = True
        db.refresh(tag)
    elif tag.deleted_at is not None:
        tag.deleted_at = None
        tag.updated_at = datetime.now(UTC)
        db.commit()
        db.refresh(tag)
        created = True
    if created:
        log_audit_event_sync(
            db, tenant_id=tenant_id,
            user_id=resolve_audit_actor(user, request),
            action="tag_created", entity_type="tag", entity_id=str(tag.id),
            details={"name": name, "via": "customers_bulk_tag"}, request=request,
        )
        db.commit()

    tagged = 0
    failed: list[str] = []
    for cid in requested:
        if cid not in live_ids:
            continue
        # CANONICAL spelling, not the caller's. `entity_id` is free-form text,
        # so an uppercase or braced UUID would write a row that
        # `_list_tags_for_entity` (which queries the lowercase canonical id)
        # can never read — and a second call with the canonical form would add
        # a DUPLICATE assignment, defeating the idempotency below. Found by the
        # adversarial audit with an uppercase id: tagged:1, then unreadable.
        try:
            _assign_tag(
                db, tenant_id=tenant_id, entity_type="customer",
                entity_id=str(as_uuid[cid]), tag_id=tag.id, user=user, request=request,
            )
        except Exception:
            # AUDIT #3: there is no transaction around this loop — `_assign_tag`
            # commits per assignment. A raise partway used to abandon the batch
            # with a 500, losing exactly the per-customer reporting this handler
            # exists to provide. Record the failure and keep going; the caller
            # gets counts plus the ids that did not land.
            log.exception("bulk_tag_assign_failed", extra={"customer_id": cid})
            failed.append(cid)
            continue
        tagged += 1

    log.info(
        "customers_bulk_tag", extra={"tenant_id": tenant_id, "tag": name,
                                     "tagged": tagged, "missing": len(missing),
                                     "failed": len(failed)},
    )
    # Real counts, not an echo of what was asked for. `missing` is returned so
    # the UI can say "4 of 5" instead of a blanket success.
    return {
        "ok": True,
        "tag": {"id": str(tag.id), "name": tag.name, "created": created},
        "tagged": tagged,
        "requested": len(requested),
        "not_found": missing,
        "failed": failed,
    }


@router.get("/api/jobs/{job_id}/line-items")
def job_line_items(job_id: str, user: dict = Depends(get_current_user), db: Session = Depends(get_db)):
    try:
        from gdx_dispatch.models.tenant_models import InvoiceLine
        rows = db.execute(
            select(InvoiceLine).join(Invoice, InvoiceLine.invoice_id == Invoice.id).where(
                Invoice.job_id == job_id,
                Invoice.deleted_at.is_(None),
            ).order_by(InvoiceLine.sort_order)
        ).scalars().all()
        return {"items": [{"id": str(r.id), "description": r.description, "quantity": r.quantity, "unit_price": float(r.unit_price or 0), "line_total": float(r.line_total or 0), "created_at": str(r.created_at) if r.created_at else None} for r in rows], "total": len(rows)}
    except Exception:
        log.exception("job_line_items_query_failed")
        return {"items": [], "total": 0}


@router.post("/api/jobs/{job_id}/line-items", status_code=201)
def create_job_line_item(job_id: str, request: Request, payload: dict, user: dict = Depends(get_current_user), db: Session = Depends(get_db)):
    tenant_id = company_id()
    user_id = user.get("sub") or user.get("user_id") or "system"
    invoice_id = payload.get("invoice_id")
    if not invoice_id:
        raise HTTPException(400, "invoice_id required")
    # UUID object for the column, string for the audit row and the response
    # body. `InvoiceLine.id` is Uuid(as_uuid=True), whose bind processor is
    # dialect-specific: Postgres has a native uuid type and takes a string,
    # SQLite stores CHAR(32) and calls `value.hex`, raising AttributeError.
    # The handler already coerces `invoice_id` below for the same reason; its
    # own primary key was missed. Same shape as #631 in routers/campaigns.py.
    new_uuid = uuid4()
    new_id = str(new_uuid)
    # This handler takes a raw dict, so InvoiceLineCreateIn's `gt=0` never ran
    # here: it was the one writer in the app that could put a 0 on an invoice
    # line, and a 0 line is one the invoice API itself refuses (#560).
    _raw_qty = payload.get("quantity", 1)
    try:
        qty = int(_raw_qty)
        # int() truncates, so 2.9 would silently bill 2 — compare against the
        # real number. Both calls raise OverflowError on an infinity or a
        # 400-digit integer (json.loads accepts `Infinity`), which is bad input
        # answered with a 422, not an unhandled 500.
        _is_whole = qty == float(_raw_qty)
    except (TypeError, ValueError, OverflowError):
        raise HTTPException(422, "quantity must be a whole number") from None
    if not _is_whole:
        raise HTTPException(422, "quantity must be a whole number")
    if qty < 1:
        raise HTTPException(422, "quantity must be at least 1 — a line with no quantity is not billed as 1")
    price = float(payload.get("unit_price", 0))
    line_total = qty * price
    now = datetime.now(UTC)
    ensure_audit_table(db)  # before staging: its first run on an engine commits
    try:
        from uuid import UUID as _UUID

        from gdx_dispatch.models.tenant_models import InvoiceLine
        try:
            _inv_uuid = _UUID(invoice_id)
        except (ValueError, AttributeError):
            raise HTTPException(400, "invalid invoice_id") from None
        line = InvoiceLine(
            id=new_uuid,
            company_id=tenant_id,
            invoice_id=_inv_uuid,
            description=payload.get("description", ""),
            quantity=qty,
            unit_price=price,
            line_total=line_total,
            sort_order=999,
            created_at=now,
        )
        db.add(line)
        # Same commit as the change (#700): get_db() closes without committing.
        log_audit_event_sync(db, tenant_id=tenant_id, user_id=user_id, action="create_line_item", entity_type="invoice_line", entity_id=new_id, details={"job_id": job_id, "invoice_id": invoice_id}, request=request)
        db.commit()
    except HTTPException:
        raise
    except Exception:
        log.exception("create_line_item_failed")
        db.rollback()
        raise HTTPException(500, "Failed to create line item") from None
    return {"ok": True, "id": new_id}


