"""SS-17 slice C — ENABLE RLS + CREATE policies on REMAINING tenant-scoped tables.

Chains directly off SS-16 (``down_revision = "ss16_rls_critical"``) so the
two RLS batches apply as a pair when the supervisor integrates them into
the main migration chain at end-of-sprint.

Source of truth for the table list: :data:`gdx_dispatch.tools.rls_remaining_tables.REMAINING_TABLES`.
Source of truth for policy SQL: :func:`gdx_dispatch.tools.rls_render.render_policies`
(SS-16's renderer — NOT modified by SS-17).

Guarded by ``_is_postgres()``: on sqlite (the unit-test backend) the whole
upgrade is a no-op, because RLS is a PG feature. PG integration tests live
in ``gdx_dispatch/tests/test_rls_remaining_integration.py`` and run against a real
PG instance when ``GDX_TEST_CONTROL_DB_URL`` is set.

Resilience
----------
Because this migration touches ~100 tables, per-table failures need visible
attribution. Each CREATE POLICY block runs inside a try/except that
re-raises with the table name in the message — never silently skipping.
If any table in the list doesn't yet exist in a given environment (e.g.
staging lagging main), the operator sees "RLS enable failed on <table>"
instead of a bare psycopg traceback.

Revision ID: ss17_rls_remaining
Down revision: ss16_rls_critical (chains after SS-16)
"""
from __future__ import annotations

import logging

from alembic import op
from sqlalchemy import inspect

from gdx_dispatch.migrations._rls_frozen import REMAINING_TABLES
from gdx_dispatch.tools.rls_render import render_policies

logger = logging.getLogger(__name__)

# NOTE: revision id uses the sprint slug so the supervisor can grep-find
# and retarget down_revision without guessing. Keep stable.
revision = "ss17_rls_remaining"
down_revision = "ss16_rls_critical"
branch_labels = None
depends_on = None


def _is_postgres() -> bool:
    bind = op.get_bind()
    return bind.dialect.name == "postgresql"


def upgrade() -> None:
    if not _is_postgres():
        logger.info("ss17_rls_remaining: non-PG dialect — skipping (no-op)")
        return

    # REMAINING_TABLES live on the TENANT-scoped DB. When this migration
    # runs against the CONTROL plane DB those tables don't exist — skip
    # them silently, tenant DBs will apply separately (same pattern as
    # SS-16). See SS-16 migration for rationale.
    inspector = inspect(op.get_bind())
    existing_tables = set(inspector.get_table_names())
    for table, select_extra_predicate, soft_delete_column in REMAINING_TABLES:
        if table not in existing_tables:
            continue
        # Also require company_id column — REMAINING_TABLES was auto-
        # generated by grepping tenant_models.py, but drift can land a
        # table here that lacks the tenant-scope key (e.g., app_settings).
        # Rendered policy would fail CREATE POLICY with "column does not
        # exist". Skip + let the coverage test surface the drift.
        columns = {c["name"] for c in inspector.get_columns(table)}
        if "company_id" not in columns:
            continue
        sql = render_policies(table, select_extra_predicate, soft_delete_column)
        try:
            op.execute(sql)
        except Exception:
            # Re-raise with the table name bolted on so the operator can
            # identify which of the ~100 tables blew up without diffing
            # the REMAINING_TABLES list against the traceback.
            logger.exception("ss17_rls_remaining: RLS enable failed on %s", table)
            raise


def downgrade() -> None:
    if not _is_postgres():
        return

    inspector = inspect(op.get_bind())
    existing_tables = set(inspector.get_table_names())
    for table, _, _ in REMAINING_TABLES:
        if table not in existing_tables:
            continue
        # Reverse order: drop policies before disabling RLS (DISABLE
        # alone does not drop the policy objects). Same shape as SS-16.
        try:
            op.execute(f"DROP POLICY IF EXISTS {table}_select_policy ON {table};")
            op.execute(f"DROP POLICY IF EXISTS {table}_write_insert_policy ON {table};")
            op.execute(f"DROP POLICY IF EXISTS {table}_write_policy ON {table};")
            op.execute(f"DROP POLICY IF EXISTS {table}_write_delete_policy ON {table};")
            op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")
        except Exception:
            logger.exception("ss17_rls_remaining: downgrade failed on %s", table)
            raise
